services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html           
      - ./backend/.env:/var/www/html/.env 
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:...
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: skyllrnews_db
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network
    depends_on:
      - backend

  webserver:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: skyllrnews_db
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

networks:
  app-network:
    driver: bridge